version: '3.8'

services:
  epaper-junction-relay:
    image: YOUR_USERNAME/junctionrelay-epaper:latest
    container_name: epaper-junction-relay
    
    # Network configuration
    ports:
      - "80:80"
    
    # Device access for Raspberry Pi 5 GPIO/SPI
    devices:
      - /dev/spidev0.0:/dev/spidev0.0
      - /dev/spidev0.1:/dev/spidev0.1
      - /dev/gpiomem0:/dev/gpiomem0      # Pi 5 primary GPIO
      - /dev/gpiomem1:/dev/gpiomem1      # Pi 5 additional GPIO
      - /dev/gpiomem2:/dev/gpiomem2      # Pi 5 additional GPIO  
      - /dev/gpiomem3:/dev/gpiomem3      # Pi 5 additional GPIO
      - /dev/gpiomem4:/dev/gpiomem4      # Pi 5 additional GPIO
      - /dev/gpiochip0:/dev/gpiochip0    # Pi 5 GPIO chip
      - /dev/mem:/dev/mem                # Memory access
    
    # Required for GPIO access
    privileged: true
    
    # Add user to GPIO and SPI groups (Pi 5 group IDs)
    group_add:
      - "993"  # gpio group
      - "995"  # spi group
    
    # Volume mounts
    volumes:
      - ./config:/app/config
      - ./logs:/app/logs
      - /opt/epaper/lib:/app/lib  # Mount Waveshare library directory
      - /dev:/dev       # Device access
      - /sys:/sys       # System access for GPIO
      - /proc:/proc     # Process access
      - /proc/device-tree:/proc/device-tree:ro  # Pi model detection
    
    # Environment variables
    environment:
      - PYTHONUNBUFFERED=1
      - DEVICE_NAME=EPaper-Display-${HOSTNAME:-001}
      - LOG_LEVEL=INFO
      - GPIOZERO_PIN_FACTORY=rpigpio
      - PIGPIO_ADDR=127.0.0.1
      - PIGPIO_PORT=8888
      
    # Restart policy
    restart: unless-stopped
    
    # Health check
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/api/health/heartbeat"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    
    # Resource limits (adjust for Pi)
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    
    # Logging configuration
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"