# Portainer Stack for catapultcase/junctionrelay-epaper
# Copy this into Portainer -> Stacks -> Add Stack -> Web Editor

version: '3.8'

services:
  epaper-junction-relay:
    image: catapultcase/junctionrelay-epaper:latest
    container_name: epaper-junction-relay-${STACK_NAME:-default}
    
    ports:
      - "${HTTP_PORT:-80}:80"
    
    devices:
      - /dev/spidev0.0:/dev/spidev0.0
      - /dev/spidev0.1:/dev/spidev0.1  
      - /dev/gpiomem:/dev/gpiomem
      - /dev/mem:/dev/mem
    
    privileged: true
    
    volumes:
      - epaper_config:/app/config
      - epaper_logs:/app/logs
      - /opt/epaper/lib:/app/lib:ro  # Read-only Waveshare library mount
      - /dev:/dev
      - /sys:/sys       # System access for GPIO
      - /proc:/proc     # Process access
    
    environment:
      - PYTHONUNBUFFERED=1
      - DEVICE_NAME=${DEVICE_NAME:-EPaper-Display}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - HTTP_PORT=80
      - GPIOZERO_PIN_FACTORY=rpigpio
      
    restart: unless-stopped
    
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/api/health/heartbeat"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    
    deploy:
      resources:
        limits:
          memory: ${MEMORY_LIMIT:-512M}
        reservations:
          memory: ${MEMORY_RESERVATION:-256M}
    
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  epaper_config:
    driver: local
  epaper_logs:
    driver: local

# Environment Variables for Portainer:
# DEVICE_NAME: EPaper-Kitchen
# HTTP_PORT: 80  
# LOG_LEVEL: INFO
# MEMORY_LIMIT: 512M
# MEMORY_RESERVATION: 256M